name = "strategy"
description = "Property-based testing framework"
version = "0.1.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["test", "property", "testing"]

[[depends-on]]
gnat = ">=15"


[[actions]]
type = "test"
command = ["gprbuild", "-p", "-P", "tests/strategy_tests.gpr"]

[[actions]]
type = "test"
command = ["sh", "-c", "for f in $(find tests/bin -maxdepth 1 -type f -perm -111 -name 'strategy_tests-*'); do \"$f\"; done"]
